### ISSUE TITLE
Why does the merge option impact read-only lookup?

### ISSUE THREAD

**Issue by wouterbeek** [JanWielemaker/rocksdb#4]
I have created a RocksDB index that uses a merge operator to combine values.

Later, I open the RocksDB index in read-only mode and do not include the merge option (because I will not be merging any values now).  The index gives back a different number of key/value pairs now.

Why does the merge option impact read-only lookup at all?  Is this a bug or is the merge operator also needed in read-only mode?

**Comment by JanWielemaker** [comment]
Rocks doesn't (always) merge open merges when closing the database.  I general you always need the
same options, possibly except for read_only.
